Feature/fix 131 truncate
rocs-org/data-pipelines pull request #133
Opened 2022-02-08 15:53 UTC by davhin

Fixes https://github.com/rocs-org/data-pipelines/issues/131

2022-02-08 16:16 UTC, davhin commented
I moved the truncate query upstream so that is only executed once, independent of the insert. I then also remove the truncate_insert query builder since it serves no more use, and use the regular insert query instead

2022-02-09 10:06 UTC, jakobkolb requested changes
Also, add a test that writes more than 100 entries into the DB and makes sure that they actually end up there.

2022-02-09 10:06 UTC, jakobkolb commented on services/airflow/src/lib/dag_helpers/write_dataframe_to_postgres.py
> +    teardown_db_context(db_context)
```suggestion
    _connect_to_db_and_execute(
        R.always(sql.SQL("TRUNCATE TABLE {schema}.{table};").format(
            schema=sql.Identifier(schema),
            table=sql.Identifier(table),
            )
        ), 
        R.T, 
        ""
    )
```

2022-02-09 11:00 UTC, jakobkolb approved these changes
lgtm!

2022-02-09 11:00 UTC, davhin commented
> Also, add a test that writes more than 100 entries into the DB and makes sure that they actually end up there.

Done, First write adds 150 rows of data, second does 200

2022-02-09 11:02 UTC, merged