Setup clickhouse infrastructure
rocs-org/data-pipelines pull request #139
Opened 2022-02-15 09:51 UTC by jakobkolb

Fix #137

WIP:
- [ ] Setup clickhouse in airflow docker stack for testing 
- [ ] Add clickhouse helpers and migration management in library
- [ ] Add clickhouse example dag
- [ ] Add clickhouse production secrets

2022-02-17 10:00 UTC, davhin requested changes
I like it! Some minor things

- please remove the email address from the DAG arguments, as those emails will not be spent
- we still need a CLI around the clickhouse migration tool for CI/CD

2022-02-17 11:42 UTC, jakobkolb commented on services/airflow/src/dags/csv_download_to_clickhouse/csv_download_to_clickhouse.py
> +    "email": ["jakob.j.kolb@gmail.com"],
Right. Cleaned that up also in all other places.

2022-03-04 11:19 UTC, jakobkolb commented
Blocked by [this](https://github.com/rocs-org/legendary-octo-spork/issues/9)

2022-03-10 08:53 UTC, davhin commented
> @davhin Blocked by [this](https://github.com/rocs-org/legendary-octo-spork/issues/9)

fixing rn

2022-03-10 12:55 UTC, davhin commented on .gitsecret/paths/mapping.cfg
> -services/airflow/.env.prod:7ec9839812b6346213a0060da85fb73493cb211e0ab26a37ce22577e563056f9
This is probably part of the problem @jakobkolb

2022-03-10 13:39 UTC, jakobkolb commented
Superseded by #149

2022-03-10 13:39 UTC, closed without merging